#!/usr/bin/env python3
"""
install.py — put omni-team into a project and register its roles and skills
with your AI coding tools.

Standard library only (Python 3.8+). Safe to re-run: it rewrites only files it
generated itself (they carry a "generated by omni-team" marker) and refuses to
overwrite anything else unless you pass --force.

Install into ANOTHER project from this checkout (no manual copy):
    python3 /path/to/omni-team/.omni-team/install.py --dir /path/to/project
    python3 /path/to/omni-team/.omni-team/install.py init --dir /path/to/project --tools all
    python3 /path/to/omni-team/.omni-team/install.py upgrade --dir /path/to/project
  → copies the framework to <project>/.omni-team/ (an existing copy is upgraded:
    framework files replaced, project/ and runs/ never touched), then registers
    the tool adapters in <project>/.

Re-register in place (from a project that already has .omni-team/):
    python3 .omni-team/install.py                    # claude + codex (default)
    python3 .omni-team/install.py --tools claude
    python3 .omni-team/install.py --tools all        # claude, codex, gemini, agents-md
    python3 .omni-team/install.py --dry-run
    python3 .omni-team/install.py uninstall          # same as --uninstall

Commands: install (default) · init (alias of install) · upgrade (requires an
existing <project>/.omni-team/) · uninstall (adapters only; the vendored
folder is left for you to delete).

What each tool target writes (paths relative to the project root):
    claude     .claude/agents/<role>.md, .claude/skills/<skill>/SKILL.md, pointer in CLAUDE.md
    codex      .codex/agents/<role>.toml, .agents/skills/<skill>/SKILL.md, pointer in AGENTS.md
    gemini     pointer in GEMINI.md
    agents-md  pointer in AGENTS.md (Cursor, Copilot, Windsurf, Aider, Zed, Jules, … read it)
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

FRAMEWORK_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(FRAMEWORK_ROOT))

from lib import adapters, vendor  # noqa: E402
from lib.roles import RoleError, load_protocol, load_roles, load_skills  # noqa: E402

ALL_TOOLS = ("claude", "codex", "gemini", "agents-md")
DEFAULT_TOOLS = ("claude", "codex")
COMMANDS = ("install", "init", "upgrade", "uninstall")
POINTER_FILES = {"claude": "CLAUDE.md", "codex": "AGENTS.md", "gemini": "GEMINI.md", "agents-md": "AGENTS.md"}


@dataclass
class Action:
    kind: str            # write | delete | pointer | unpointer
    path: Path
    content: str = ""


class InstallError(Exception):
    pass


def parse_tiers(spec: Optional[str], default: Dict[str, str]) -> Dict[str, str]:
    """`deep=opus,standard=sonnet` → dict merged over the defaults."""
    tiers = dict(default)
    for pair in filter(None, (spec or "").split(",")):
        key, sep, value = pair.partition("=")
        if not sep or key.strip() not in default:
            raise InstallError(f"bad tier mapping '{pair}' (expected deep=…, standard=…, fast=…)")
        tiers[key.strip()] = value.strip()
    return tiers


def _stale_managed(directory: Path, pattern: str, keep: List[Path]) -> List[Path]:
    if not directory.exists():
        return []
    return [p for p in directory.glob(pattern) if p not in keep and adapters.is_managed(p)]


def plan_claude(root: Path, args: argparse.Namespace) -> List[Action]:
    protocol, models = load_protocol(), parse_tiers(args.claude_models, adapters.DEFAULT_CLAUDE_MODELS)
    agents_dir, skills_dir = root / ".claude" / "agents", root / ".claude" / "skills"
    actions = [Action("write", agents_dir / f"{r.name}.md", adapters.render_claude_agent(r, protocol, models))
               for r in load_roles()]
    actions += [Action("write", skills_dir / s.name / "SKILL.md", adapters.render_skill(s)) for s in load_skills()]
    keep = [a.path for a in actions]
    actions += [Action("delete", p) for p in _stale_managed(agents_dir, "*.md", keep)]
    actions += [Action("delete", p) for p in _stale_managed(skills_dir, "*/SKILL.md", keep)]
    return actions


def plan_codex(root: Path, args: argparse.Namespace) -> List[Action]:
    protocol, efforts = load_protocol(), parse_tiers(args.codex_effort, adapters.DEFAULT_CODEX_EFFORT)
    agents_dir, skills_dir = root / ".codex" / "agents", root / ".agents" / "skills"
    actions = [Action("write", agents_dir / f"{r.name}.toml", adapters.render_codex_agent(r, protocol, efforts))
               for r in load_roles()]
    actions += [Action("write", skills_dir / s.name / "SKILL.md", adapters.render_skill(s)) for s in load_skills()]
    keep = [a.path for a in actions]
    actions += [Action("delete", p) for p in _stale_managed(agents_dir, "*.toml", keep)]
    actions += [Action("delete", p) for p in _stale_managed(skills_dir, "*/SKILL.md", keep)]
    return actions


PLANNERS = {"claude": plan_claude, "codex": plan_codex}


def plan_install(root: Path, tools: List[str], args: argparse.Namespace) -> List[Action]:
    actions: List[Action] = []
    for tool in tools:
        if tool in PLANNERS:
            actions += PLANNERS[tool](root, args)
    if not args.no_pointer:
        for name in dict.fromkeys(POINTER_FILES[t] for t in tools):
            actions.append(Action("pointer", root / name))
    return actions


def plan_uninstall(root: Path, tools: List[str]) -> List[Action]:
    dirs = {
        "claude": [(root / ".claude" / "agents", "*.md"), (root / ".claude" / "skills", "*/SKILL.md")],
        "codex": [(root / ".codex" / "agents", "*.toml"), (root / ".agents" / "skills", "*/SKILL.md")],
    }
    actions = [Action("delete", p) for t in tools for d, pat in dirs.get(t, []) for p in _stale_managed(d, pat, [])]
    for name in dict.fromkeys(POINTER_FILES[t] for t in tools):
        if (root / name).exists():
            actions.append(Action("unpointer", root / name))
    return actions


def _check_conflicts(actions: List[Action], force: bool) -> None:
    conflicts = [a.path for a in actions if a.kind == "write" and a.path.exists() and not adapters.is_managed(a.path)]
    if conflicts and not force:
        listing = "\n".join(f"  - {p}" for p in conflicts)
        raise InstallError(
            "these files exist and were not generated by omni-team:\n"
            f"{listing}\nRename them, or re-run with --force to overwrite."
        )


def _apply(action: Action) -> str:
    path = action.path
    if action.kind == "write":
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(action.content, encoding="utf-8")
        return "wrote"
    if action.kind == "delete":
        path.unlink()
        if path.name == "SKILL.md" and not any(path.parent.iterdir()):
            path.parent.rmdir()
        return "removed"
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if action.kind == "pointer":
        path.write_text(adapters.upsert_block(existing, adapters.pointer_block()), encoding="utf-8")
        return "pointer"
    remaining = adapters.remove_block(existing or "")
    if remaining.strip():
        path.write_text(remaining, encoding="utf-8")
        return "unpointer"
    path.unlink()
    return "removed"


def _display(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("command", nargs="?", default="install", choices=COMMANDS,
                   help="install (default) | init (= install) | upgrade | uninstall")
    p.add_argument("--dir", type=Path,
                   help="target project root: vendor the framework into <dir>/.omni-team/ and install there")
    p.add_argument("--tools", default=",".join(DEFAULT_TOOLS),
                   help=f"comma list of {', '.join(ALL_TOOLS)}, or 'all' (default: %(default)s)")
    p.add_argument("--project-root", type=Path,
                   help="register adapters into this root WITHOUT copying the framework "
                        "(default: the folder containing .omni-team/)")
    p.add_argument("--claude-models", help="tier→model, e.g. deep=opus,standard=sonnet,fast=haiku")
    p.add_argument("--codex-effort", help="tier→reasoning effort, e.g. deep=high,standard=medium,fast=low")
    p.add_argument("--no-pointer", action="store_true", help="do not touch CLAUDE.md / AGENTS.md / GEMINI.md")
    p.add_argument("--uninstall", action="store_true", help="remove everything this script generated")
    p.add_argument("--force", action="store_true",
                   help="overwrite same-named files not generated by omni-team; allow a vendor downgrade")
    p.add_argument("--dry-run", action="store_true", help="show the plan, write nothing")
    return p.parse_args(argv)


def _git_root_warning(root: Path) -> Optional[str]:
    try:
        done = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=str(root),
                              capture_output=True, text=True, check=False)
    except OSError:
        return "git not found — the orchestrator needs git to compute review scopes"
    if done.returncode != 0:
        return f"{root} is not a git repository — run `git init` there before using the orchestrator"
    top = Path(done.stdout.strip()).resolve()
    if top != root:
        return f"{root} is not the git root ({top}); omni-team works best at the repository root"
    return None


def plan_vendor(args: argparse.Namespace, root: Path) -> Optional[vendor.VendorPlan]:
    """Validate everything about the copy BEFORE anything is written."""
    if not args.dir or args.uninstall:
        if args.command == "upgrade":
            raise InstallError("upgrade needs --dir <project> (the project to upgrade)")
        return None
    vplan = vendor.plan(FRAMEWORK_ROOT, root, force=args.force)
    if args.command == "upgrade" and vplan.mode == "fresh":
        raise vendor.VendorError(f"nothing to upgrade: {vplan.target} does not exist (use install)")
    return vplan


def run_vendor(vplan: vendor.VendorPlan, args: argparse.Namespace, root: Path) -> None:
    """Report and (unless --dry-run) apply the copy / upgrade of <root>/.omni-team/."""
    prefix = "[dry-run] " if args.dry_run else ""
    if vplan.mode == "same":
        print(f"vendor: {vplan.target} is this framework itself — nothing to copy")
        return
    versions = f"v{vplan.from_version} → v{vplan.to_version}" if vplan.mode == "upgrade" else f"v{vplan.to_version}"
    print(f"{prefix}vendor ({vplan.mode}, {versions}) → {vplan.target}")
    print(f"   {prefix}added {len(vplan.added)} · updated {len(vplan.updated)} · removed {len(vplan.removed)}"
          + ("  (project/ and runs/ preserved)" if vplan.mode == "upgrade" else ""))
    for path in vplan.removed:
        print(f"   {prefix}removed   {_display(path, root)}")
    if not args.dry_run:
        vendor.apply(vplan)


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    if args.command == "uninstall":
        args.uninstall = True
    tools = list(ALL_TOOLS) if args.tools.strip() == "all" else [t.strip() for t in args.tools.split(",") if t.strip()]
    unknown = [t for t in tools if t not in ALL_TOOLS]
    if unknown:
        print(f"❌ unknown tool(s): {', '.join(unknown)} (choose from {', '.join(ALL_TOOLS)})", file=sys.stderr)
        return 2
    if args.dir and args.project_root:
        print("❌ use either --dir (copy + install) or --project-root (install only), not both", file=sys.stderr)
        return 2
    root = (args.dir or args.project_root or FRAMEWORK_ROOT.parent).expanduser().resolve()
    try:
        vplan = plan_vendor(args, root)
        actions = plan_uninstall(root, tools) if args.uninstall else plan_install(root, tools, args)
        if not args.uninstall:
            _check_conflicts(actions, args.force)
    except (RoleError, InstallError, vendor.VendorError) as exc:
        print(f"❌ {exc}", file=sys.stderr)
        return 2

    if vplan is not None:
        run_vendor(vplan, args, root)
        warning = _git_root_warning(root)
        if warning:
            print(f"   ⚠️  {warning}")

    print(f"omni-team {'uninstall' if args.uninstall else 'install'} → {root}  (tools: {', '.join(tools)})")
    for action in actions:
        label = action.kind if args.dry_run else _apply(action)
        print(f"   {'[dry-run] ' if args.dry_run else ''}{label:9s} {_display(action.path, root)}")
    if args.uninstall and args.dir:
        print(f"\nThe vendored framework stays in {root / vendor.FOLDER}; delete it yourself if you no longer need it.")
    if not args.uninstall and not args.dry_run:
        print(f"\nNext: open {root} in your agent, run the `omni-setup` skill once (optional), then `omni-task <request>`.")
        print(f"Guide: {_display(root / vendor.FOLDER / 'README.md', Path.cwd())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
