#!/usr/bin/env python3
"""
install.py — put omni-team into a project and register its roles and skills
with your AI coding tools.

Standard library only (Python 3.8+). Safe to re-run: it rewrites only files it
generated itself (they carry a "generated by omni-team" marker) and refuses to
overwrite anything else unless you pass --force.

Install into ANOTHER project from this checkout (no manual copy):
    python3 /path/to/omni-team/.omni-team/install.py --dir /path/to/project
    python3 /path/to/omni-team/.omni-team/install.py init --dir /path/to/project --tools all
    python3 /path/to/omni-team/.omni-team/install.py upgrade --dir /path/to/project
  → copies the framework's RUNTIME SET to <project>/.omni-team/ (agent manual,
    roles, orchestrator, defaults, user docs; --full copies everything), or
    upgrades an existing copy (framework files replaced, files it no longer ships
    removed, project/ and runs/ never touched), then registers the tool adapters
    in <project>/. The installer itself stays here, in the omni-team checkout.

Re-register in place (from a project that already has .omni-team/):
    python3 .omni-team/install.py                    # claude + codex (default)
    python3 .omni-team/install.py --tools claude
    python3 .omni-team/install.py --tools all        # claude, codex, gemini, agents-md
    python3 .omni-team/install.py --dry-run
    python3 .omni-team/install.py uninstall          # same as --uninstall

Commands: install (default) · init (alias of install) · upgrade (requires an
existing <project>/.omni-team/) · uninstall (adapters only; the vendored
folder is left for you to delete).

What each tool target writes (paths relative to the project root):
    claude     .claude/agents/<role>.md, .claude/skills/<skill>/SKILL.md, pointer in CLAUDE.md
    codex      .codex/agents/<role>.toml, .agents/skills/<skill>/SKILL.md, pointer in AGENTS.md
    gemini     pointer in GEMINI.md
    agents-md  pointer in AGENTS.md (Cursor, Copilot, Windsurf, Aider, Zed, Jules, … read it)
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

FRAMEWORK_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(FRAMEWORK_ROOT))

from lib import adapters, vendor  # noqa: E402
from lib.roles import RoleError, load_protocol, load_roles, load_skills  # noqa: E402

ALL_TOOLS = ("claude", "codex", "gemini", "agents-md")
DEFAULT_TOOLS = ("claude", "codex")
COMMANDS = ("install", "init", "upgrade", "uninstall")
TOOLS_WITHOUT_SKILLS = ("gemini", "agents-md")   # these get skills/ vendored as plain playbooks
POINTER_FILES = {"claude": "CLAUDE.md", "codex": "AGENTS.md", "gemini": "GEMINI.md", "agents-md": "AGENTS.md"}


@dataclass
class Action:
    kind: str                    # write | copy | delete | pointer | unpointer
    path: Path
    content: str = ""
    src: Optional[Path] = None   # copy: file copied byte-for-byte (skill scripts, data, licences)
    stop: Optional[Path] = None  # delete: prune emptied parent folders up to (not including) this one


class InstallError(Exception):
    pass


def parse_tiers(spec: Optional[str], default: Dict[str, str]) -> Dict[str, str]:
    """`deep=opus,standard=sonnet` → dict merged over the defaults."""
    tiers = dict(default)
    for pair in filter(None, (spec or "").split(",")):
        key, sep, value = pair.partition("=")
        if not sep or key.strip() not in default:
            raise InstallError(f"bad tier mapping '{pair}' (expected deep=…, standard=…, fast=…)")
        tiers[key.strip()] = value.strip()
    return tiers


def _stale_managed(directory: Path, pattern: str, keep: List[Path]) -> List[Path]:
    if not directory.exists():
        return []
    return [p for p in directory.glob(pattern) if p not in keep and adapters.is_managed(p)]


def _stale_skill_files(skills_dir: Path, keep: List[Path]) -> List[Action]:
    """Every file inside a managed skill folder (its SKILL.md carries the marker) that is not planned."""
    if not skills_dir.exists():
        return []
    stale = []
    for skill_md in skills_dir.glob("*/SKILL.md"):
        if adapters.is_managed(skill_md):
            stale += [p for p in skill_md.parent.rglob("*") if p.is_file() and p not in keep]
    return [Action("delete", p, stop=skills_dir) for p in sorted(stale)]


def selected_skills(args: argparse.Namespace) -> list:
    skills = load_skills()
    if args.skills in (None, "", "all"):
        return skills
    wanted = [n.strip() for n in args.skills.split(",") if n.strip()]
    unknown = sorted(set(wanted) - {s.name for s in skills})
    if unknown:
        raise InstallError(f"unknown skill(s): {', '.join(unknown)} (available: {', '.join(s.name for s in skills)})")
    return [s for s in skills if s.name in wanted]


def _skill_actions(skills_dir: Path, args: argparse.Namespace) -> List[Action]:
    actions = []
    for skill in selected_skills(args):
        actions.append(Action("write", skills_dir / skill.name / "SKILL.md", adapters.render_skill(skill)))
        actions += [Action("copy", skills_dir / skill.name / rel, src=skill.source.parent / rel, stop=skills_dir)
                    for rel in vendor.framework_files(skill.source.parent) if rel != Path("SKILL.md")]
    return actions


def _plan_tool(agents_dir: Path, agent_suffix: str, render, skills_dir: Path, args: argparse.Namespace) -> List[Action]:
    actions = [Action("write", agents_dir / f"{r.name}{agent_suffix}", render(r)) for r in load_roles()]
    actions += _skill_actions(skills_dir, args)
    keep = [a.path for a in actions]
    actions += [Action("delete", p) for p in _stale_managed(agents_dir, f"*{agent_suffix}", keep)]
    return actions + _stale_skill_files(skills_dir, keep)


def plan_claude(root: Path, args: argparse.Namespace) -> List[Action]:
    protocol, models = load_protocol(), parse_tiers(args.claude_models, adapters.DEFAULT_CLAUDE_MODELS)
    return _plan_tool(root / ".claude" / "agents", ".md",
                      lambda r: adapters.render_claude_agent(r, protocol, models), root / ".claude" / "skills", args)


def plan_codex(root: Path, args: argparse.Namespace) -> List[Action]:
    protocol, efforts = load_protocol(), parse_tiers(args.codex_effort, adapters.DEFAULT_CODEX_EFFORT)
    return _plan_tool(root / ".codex" / "agents", ".toml",
                      lambda r: adapters.render_codex_agent(r, protocol, efforts), root / ".agents" / "skills", args)


PLANNERS = {"claude": plan_claude, "codex": plan_codex}


def plan_install(root: Path, tools: List[str], args: argparse.Namespace) -> List[Action]:
    actions: List[Action] = []
    for tool in tools:
        if tool in PLANNERS:
            actions += PLANNERS[tool](root, args)
    if not args.no_pointer:
        for name in dict.fromkeys(POINTER_FILES[t] for t in tools):
            actions.append(Action("pointer", root / name))
    return actions


def plan_uninstall(root: Path, tools: List[str]) -> List[Action]:
    dirs = {
        "claude": (root / ".claude" / "agents", "*.md", root / ".claude" / "skills"),
        "codex": (root / ".codex" / "agents", "*.toml", root / ".agents" / "skills"),
    }
    actions: List[Action] = []
    for tool in tools:
        if tool in dirs:
            agents_dir, pattern, skills_dir = dirs[tool]
            actions += [Action("delete", p) for p in _stale_managed(agents_dir, pattern, [])]
            actions += _stale_skill_files(skills_dir, [])
    for name in dict.fromkeys(POINTER_FILES[t] for t in tools):
        if (root / name).exists():
            actions.append(Action("unpointer", root / name))
    return actions


def _check_conflicts(actions: List[Action], force: bool) -> None:
    conflicts = [a.path for a in actions if a.kind == "write" and a.path.exists() and not adapters.is_managed(a.path)]
    if conflicts and not force:
        listing = "\n".join(f"  - {p}" for p in conflicts)
        raise InstallError(
            "these files exist and were not generated by omni-team:\n"
            f"{listing}\nRename them, or re-run with --force to overwrite."
        )


def _apply(action: Action) -> str:
    path = action.path
    if action.kind == "write":
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(action.content, encoding="utf-8")
        return "wrote"
    if action.kind == "copy":
        path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(action.src, path)
        return "copied"
    if action.kind == "delete":
        path.unlink()
        parent = path.parent
        while action.stop is not None and parent != action.stop and parent.exists() and not any(parent.iterdir()):
            parent.rmdir()
            parent = parent.parent
        return "removed"
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if action.kind == "pointer":
        path.write_text(adapters.upsert_block(existing, adapters.pointer_block()), encoding="utf-8")
        return "pointer"
    remaining = adapters.remove_block(existing or "")
    if remaining.strip():
        path.write_text(remaining, encoding="utf-8")
        return "unpointer"
    path.unlink()
    return "removed"


def _report(actions: List[Action], root: Path, dry_run: bool) -> None:
    """Apply (unless dry-run) and print; files inside one skill folder are summarised on one line."""
    prefix = "[dry-run] " if dry_run else ""
    grouped: Dict[tuple, int] = {}
    for action in actions:
        label = action.kind if dry_run else _apply(action)
        if action.kind in ("copy", "delete") and action.stop is not None:
            folder = action.stop / action.path.relative_to(action.stop).parts[0]
            grouped[(label, folder)] = grouped.get((label, folder), 0) + 1
            continue
        print(f"   {prefix}{label:9s} {_display(action.path, root)}")
    for (label, folder), count in grouped.items():
        print(f"   {prefix}{label:9s} {_display(folder, root)}/  ({count} file{'s' if count > 1 else ''})")


def _display(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("command", nargs="?", default="install", choices=COMMANDS,
                   help="install (default) | init (= install) | upgrade | uninstall")
    p.add_argument("--dir", type=Path,
                   help="target project root: vendor the framework into <dir>/.omni-team/ and install there")
    p.add_argument("--tools", default=",".join(DEFAULT_TOOLS),
                   help=f"comma list of {', '.join(ALL_TOOLS)}, or 'all' (default: %(default)s)")
    p.add_argument("--project-root", type=Path,
                   help="register adapters into this root WITHOUT copying the framework "
                        "(default: the folder containing .omni-team/)")
    p.add_argument("--skills", default="all",
                   help="comma list of skills to install (default: all) — e.g. omni-task,omni-review,pm,drawio-skill")
    p.add_argument("--claude-models", help="tier→model, e.g. deep=opus,standard=sonnet,fast=haiku")
    p.add_argument("--codex-effort", help="tier→reasoning effort, e.g. deep=high,standard=medium,fast=low")
    p.add_argument("--no-pointer", action="store_true", help="do not touch CLAUDE.md / AGENTS.md / GEMINI.md")
    p.add_argument("--uninstall", action="store_true", help="remove everything this script generated")
    p.add_argument("--full", action="store_true",
                   help="with --dir: copy the whole framework (installer, tests, examples, all docs), not just the runtime set")
    p.add_argument("--force", action="store_true",
                   help="overwrite same-named files not generated by omni-team; allow a vendor downgrade")
    p.add_argument("--dry-run", action="store_true", help="show the plan, write nothing")
    return p.parse_args(argv)


def _git_root_warning(root: Path) -> Optional[str]:
    try:
        done = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=str(root),
                              capture_output=True, text=True, check=False)
    except OSError:
        return "git not found — the orchestrator needs git to compute review scopes"
    if done.returncode != 0:
        return f"{root} is not a git repository — run `git init` there before using the orchestrator"
    top = Path(done.stdout.strip()).resolve()
    if top != root:
        return f"{root} is not the git root ({top}); omni-team works best at the repository root"
    return None


def plan_vendor(args: argparse.Namespace, root: Path) -> Optional[vendor.VendorPlan]:
    """Validate everything about the copy BEFORE anything is written."""
    if not args.dir or args.uninstall:
        if args.command == "upgrade":
            raise InstallError("upgrade needs --dir <project> (the project to upgrade)")
        return None
    vplan = vendor.plan(FRAMEWORK_ROOT, root, force=args.force, full=args.full,
                        with_skills=any(t in TOOLS_WITHOUT_SKILLS for t in args.tool_list))
    if args.command == "upgrade" and vplan.mode == "fresh":
        raise vendor.VendorError(f"nothing to upgrade: {vplan.target} does not exist (use install)")
    return vplan


def run_vendor(vplan: vendor.VendorPlan, args: argparse.Namespace, root: Path) -> None:
    """Report and (unless --dry-run) apply the copy / upgrade of <root>/.omni-team/."""
    prefix = "[dry-run] " if args.dry_run else ""
    if vplan.mode == "same":
        print(f"vendor: {vplan.target} is this framework itself — nothing to copy")
        return
    versions = f"v{vplan.from_version} → v{vplan.to_version}" if vplan.mode == "upgrade" else f"v{vplan.to_version}"
    print(f"{prefix}vendor ({vplan.mode}, {vplan.flavor}, {versions}) → {vplan.target}")
    print(f"   {prefix}added {len(vplan.added)} · updated {len(vplan.updated)} · removed {len(vplan.removed)}"
          + ("  (project/ and runs/ preserved)" if vplan.mode == "upgrade" else ""))
    for path in vplan.removed:
        print(f"   {prefix}removed   {_display(path, root)}")
    if not args.dry_run:
        vendor.apply(vplan)


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    if args.command == "uninstall":
        args.uninstall = True
    tools = list(ALL_TOOLS) if args.tools.strip() == "all" else [t.strip() for t in args.tools.split(",") if t.strip()]
    unknown = [t for t in tools if t not in ALL_TOOLS]
    if unknown:
        print(f"❌ unknown tool(s): {', '.join(unknown)} (choose from {', '.join(ALL_TOOLS)})", file=sys.stderr)
        return 2
    args.tool_list = tools
    if args.dir and args.project_root:
        print("❌ use either --dir (copy + install) or --project-root (install only), not both", file=sys.stderr)
        return 2
    root = (args.dir or args.project_root or FRAMEWORK_ROOT.parent).expanduser().resolve()
    try:
        vplan = plan_vendor(args, root)
        actions = plan_uninstall(root, tools) if args.uninstall else plan_install(root, tools, args)
        if not args.uninstall:
            _check_conflicts(actions, args.force)
    except (RoleError, InstallError, vendor.VendorError) as exc:
        print(f"❌ {exc}", file=sys.stderr)
        return 2

    if vplan is not None:
        run_vendor(vplan, args, root)
        warning = _git_root_warning(root)
        if warning:
            print(f"   ⚠️  {warning}")

    print(f"omni-team {'uninstall' if args.uninstall else 'install'} → {root}  (tools: {', '.join(tools)})")
    _report(actions, root, args.dry_run)
    if args.uninstall and args.dir:
        print(f"\nThe vendored framework stays in {root / vendor.FOLDER}; delete it yourself if you no longer need it.")
    if not args.uninstall and not args.dry_run:
        print(f"\nNext: open {root} in your agent, run the `omni-setup` skill once (optional), then `omni-task <request>`.")
        manual = root / vendor.FOLDER / "AGENTS.md"
        print(f"Agent manual: {_display(manual if manual.exists() else FRAMEWORK_ROOT / 'AGENTS.md', Path.cwd())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
