"""
Tool adapters — turn canonical roles/skills into each tool's native format.

Every generated file carries MARKER so install.py can recognise (and safely
overwrite or remove) its own output without touching files a human wrote.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Optional

from .roles import Role, Skill, compose_instructions

MARKER = "generated by omni-team"
SOURCE_NOTE = "do not edit; regenerated by the omni-team installer (install.py --dir <project>)"

DEFAULT_CLAUDE_MODELS = {"deep": "opus", "standard": "sonnet", "fast": "haiku"}
DEFAULT_CODEX_EFFORT = {"deep": "high", "standard": "medium", "fast": "low"}

# `None` → omit the tools line so the agent inherits every tool, including
# whatever browser/device MCP the host has configured.
CLAUDE_TOOLS = {"read-only": "Read, Grep, Glob, Bash", "run": None}
CODEX_SANDBOX = {"read-only": "read-only", "run": "workspace-write"}

BLOCK_BEGIN = "<!-- omni-team:begin (managed by the omni-team installer; edits inside are overwritten) -->"
BLOCK_END = "<!-- omni-team:end -->"

POINTER_BODY = """## omni-team — AI review team

This repository vendors **omni-team** in `.omni-team/`: a stack-agnostic team of
delivery sub-agents (ba, architect, pm, tech-lead, code-reviewer, test-engineer,
data-reviewer, security-engineer, perf-engineer, qa-lead, smoke-tester,
release-manager).

- For any non-trivial change, follow **`.omni-team/AGENTS.md`**: define → design →
  plan → implement → Gate 0 checks → review gates → acceptance → stop at the human gate.
- Project facts and rules for the team: `.omni-team/project/profile.yaml` and
  `.omni-team/project/conventions.md`.
- Entry points: `omni-task` (full flow), `omni-plan`, `omni-review`, `omni-ship`, `omni-setup`,
  and per role `ba`, `architect`, `pm`, `release`.
- The team never commits, pushes or merges — shipping is a human decision."""


def yaml_scalar(value: str) -> str:
    """JSON strings are valid YAML double-quoted scalars and survive any punctuation."""
    return json.dumps(value, ensure_ascii=False)


def toml_basic(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '""\\"')
    return f'"""\n{escaped.rstrip()}\n"""'


def render_claude_agent(role: Role, protocol: str, models: Dict[str, str]) -> str:
    lines = [
        "---",
        f"name: {role.name}",
        f"description: {yaml_scalar(role.description)}",
    ]
    tools = CLAUDE_TOOLS[role.access]
    if tools:
        lines.append(f"tools: {tools}")
    lines += [f"model: {models[role.tier]}", "---", ""]
    header = "\n".join(lines)
    note = f"<!-- {MARKER} from .omni-team/team/{role.name}.md — {SOURCE_NOTE} -->\n\n"
    return header + note + compose_instructions(role, protocol)


def render_codex_agent(role: Role, protocol: str, efforts: Dict[str, str]) -> str:
    return (
        f"# {MARKER} from .omni-team/team/{role.name}.md — {SOURCE_NOTE}\n"
        f"name = {toml_basic(role.name)}\n"
        f"description = {toml_basic(role.description)}\n"
        f"model_reasoning_effort = {toml_basic(efforts[role.tier])}\n"
        f"sandbox_mode = {toml_basic(CODEX_SANDBOX[role.access])}\n"
        f"developer_instructions = {toml_multiline(compose_instructions(role, protocol))}\n"
    )


def render_skill(skill: Skill) -> str:
    """Same SKILL.md format works for Claude Code and Codex; add the marker after frontmatter."""
    lines = skill.text.splitlines()
    end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    note = f"<!-- {MARKER} from .omni-team/skills/{skill.name}/SKILL.md — {SOURCE_NOTE} -->"
    return "\n".join(lines[: end + 1] + ["", note] + lines[end + 1:]).rstrip() + "\n"


def pointer_block() -> str:
    return f"{BLOCK_BEGIN}\n{POINTER_BODY}\n{BLOCK_END}\n"


def upsert_block(existing: Optional[str], block: str) -> str:
    if not existing:
        return block
    start, end = existing.find(BLOCK_BEGIN), existing.find(BLOCK_END)
    if start != -1 and end != -1:
        return existing[:start] + block.rstrip("\n") + existing[end + len(BLOCK_END):]
    return existing.rstrip("\n") + "\n\n" + block


def remove_block(existing: str) -> str:
    start, end = existing.find(BLOCK_BEGIN), existing.find(BLOCK_END)
    if start == -1 or end == -1:
        return existing
    before = existing[:start].rstrip("\n")
    after = existing[end + len(BLOCK_END):].lstrip("\n")
    return (before + "\n\n" + after).strip("\n") + "\n" if before or after else ""


def is_managed(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8")[:4000]
    except (OSError, UnicodeDecodeError):
        return False
    return MARKER in head
